version: '3.8'

networks:
  csclub:

services:
    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        networks:
            - csclub
        container_name: nginx_csclub
        ports:
            - "81:80"
        volumes:
            - ./src:/var/www/html
            - ./dockerfiles/nginx/default:/etc/nginx/conf.d/default.conf
    php:
        networks:
            - csclub
        container_name: php_csclub
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        ports:
            - "9001:9000"
        volumes:
            - ./src:/var/www/html
        build:
            context: .
            dockerfile: ./dockerfiles/php.dockerfile

    composer:
        networks:
            - csclub
        volumes:
            - ./src:/app
        depends_on:
            - nginx
        container_name: composer_csclub
        build:
            context: .
            dockerfile: ./dockerfiles/composer.dockerfile
    npm:
        image: node:15.1.0-alpine3.10
        networks:
            - csclub
        volumes:
            - ./src:/app
        container_name: npm_csclub
        depends_on:
            - nginx
        working_dir: /app
        command: ["/app/npm.sh"]
    artisan:
        depends_on:
            - composer
        networks:
            - csclub
        container_name: artisan_csclub
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./src:/var/www/html
        build:
            context: .
            dockerfile: ./dockerfiles/php.dockerfile
        working_dir: /var/www/html/
        command: ["/var/www/html/artisan.sh"]
