version: '3.8'

networks:
    csclub:

services:
    nginx:
        image: nginx:stable-alpine
        depends_on:
            - php
        networks:
            - csclub
        container_name: nginx_csclub
        ports:
            - "81:80"
        volumes:
            - ./src:/var/www/html
            - ./dockerfiles/nginx/default:/etc/nginx/conf.d/default.conf

    php:
        networks:
            - csclub
        container_name: php_csclub
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        ports:
            - "9001:9000"
        volumes:
            - ./src:/var/www/html
        build:
            context: .
            dockerfile: ./dockerfiles/php.dockerfile
        dns:
            - 1.1.1.1
            - 1.0.0.1
    composer:
        networks:
            - csclub
        volumes:
            - ./src:/app
        depends_on:
            - nginx
        container_name: composer_csclub
        build:
            context: .
            dockerfile: ./dockerfiles/composer.dockerfile
    npm:
      image: node:13.7
      container_name: npm_csclub
      volumes:
        - ./src:/app
      working_dir: /app
      command: ["/app/npm-dev.sh"]
      depends_on:
        - nginx

    artisan:
        networks:
            - csclub
        container_name: artisan_csclub
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./src:/var/www/html
        build:
            context: .
            dockerfile: ./dockerfiles/php.dockerfile
        working_dir: /var/www/html/
        entrypoint: ['php', '/var/www/html/artisan']
